### ISSUE TITLE
TAPI stack does not make copy of the send file

### ISSUE THREAD

**Issue by MurthyVadapalli** [android-rcs/rcsjta#187]
TAPI stack does not make a copy of file sent from client messaging application.
So if a user deletes the original file then the file message will not be able to show the content as stack doesn't makes a copy of it.
Ideally stack must make a copy of it in it's private storage and allow access to it via content uri.
Moreover, while receiving the file transfer invite on downloading the file, stack must save it in private storage and allow access to it using content uri.

**Comment by MurthyVadapalli** [comment]
Proposed Solution :
Fixed this problem by creating new folder named "sent" inside all
rcs sub-directories like rcs/photos/sent/, rcs/videos/sent/,
rcs/files/sent/ and included a file ".nomedia" in these folders
inorder to avoid showing these files in Album.

The Patch will be submitted for review.

**Comment by yplo6403** [comment]
Copy of sent files implemented by following commits:
776a365754536f4276e462f65a678a2ed32b487e
cb4a656d2ff53bd6eb71fc5107c257341757efd8

**Comment by yplo6403** [comment]
Patch is not complete since problem still exist for image sharing
